// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV_cKVlaVixHBkRWgDSrMeJIcjQsUG2pY',
    appId: '1:467067785909:web:14800f7d1f74ed2e31a4fc',
    messagingSenderId: '467067785909',
    projectId: 'instaclass-3c895',
    authDomain: 'instaclass-3c895.firebaseapp.com',
    storageBucket: 'instaclass-3c895.firebasestorage.app',
    measurementId: 'G-2411EKZDZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkkeJNXZ8UtdWhAOPOVtJlpTjA2Imglrs',
    appId: '1:467067785909:android:6a9934cf3de2b24c31a4fc',
    messagingSenderId: '467067785909',
    projectId: 'instaclass-3c895',
    storageBucket: 'instaclass-3c895.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv54Rxz5GpMegZWBZJ9yTA1zfqBhMXquk',
    appId: '1:467067785909:ios:b59f9689e07c5ab531a4fc',
    messagingSenderId: '467067785909',
    projectId: 'instaclass-3c895',
    storageBucket: 'instaclass-3c895.firebasestorage.app',
    iosBundleId: 'com.example.syriaapp',
  );
}
